apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ .Values.name }}
      namespace: dev-pcc-bordeaux
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: mtr.external.otc.telekomcloud.com/dvershin/echo:latest
        ports:
        - containerPort: 8080
        env:
          - name:  ECHO_STRING
            value: {{ .Values.echo }}
 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
spec:
  rules:
  - host: {{ .Values.name }}.tifapis.de.t-internal.com
    http:
     paths:
     - path: /
       backend:
        serviceName: {{ .Values.name }}
        servicePort: 80
